### ISSUE TITLE
How about listing databases for entering direct on?

### ISSUE THREAD

**Issue by heliohead** [payers1/alfred-postico-favorites-workflow#1]
I realy like your workflow, thanks for sharing, every time i entering to a Postico conection i need to chose what data base i wanna  inspect, entering direct on database on a alfred list will be very handy.

Tks

**Comment by payers1** [comment]
I think you'll have to set that up when you're creating favorites in Postico by entering the database name in the database field (highlighted)

<img width="644" alt="screen shot 2017-03-07 at 10 46 20 am" src="https://cloud.githubusercontent.com/assets/11546231/23664367/5feadbc0-0323-11e7-872a-25a3cae1bfd2.png">

**Comment by heliohead** [comment]
OH! my bad, sorry   

Thank you again
